version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8080:80"  # Maps port 80 of the container to port 8080 on your host

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
